// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasks_For_ITI_MVC.Data;

#nullable disable

namespace Tasks_For_ITI_MVC.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250812070057_intailProductmaigaration")]
    partial class intailProductmaigaration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tasks_For_ITI_MVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A powerful laptop for work and gaming.",
                            ImageUrl = "/images/laptop.jpg",
                            Name = "Laptop",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A modern smartphone with high-quality camera.",
                            ImageUrl = "/images/phone.jpg",
                            Name = "Smartphone",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wireless headphones with noise cancellation.",
                            ImageUrl = "/images/headphones.jpg",
                            Name = "Headphones",
                            Price = 1200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
